// flow-typed signature: 83ab8b9297162b64886cc8abd139ef8f
// flow-typed version: <<STUB>>/postcss-prepend-imports_v^1.0.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-prepend-imports'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-prepend-imports' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-prepend-imports/__tests__/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-prepend-imports/__tests__/test.js' {
  declare module.exports: $Exports<'postcss-prepend-imports/__tests__/test'>;
}
declare module 'postcss-prepend-imports/index' {
  declare module.exports: $Exports<'postcss-prepend-imports'>;
}
declare module 'postcss-prepend-imports/index.js' {
  declare module.exports: $Exports<'postcss-prepend-imports'>;
}
